### ISSUE TITLE
[wishlist] Segment the output of ls

### ISSUE THREAD

**Issue by inducer** [bram85/topydo#112] opened 2016-02-10 18:22 UTC
It'd be great if the output of `ls` would allow "segmentation" by one or more criteria.

What I'm looking for is something like:

```
prio:B
-------

due:2016-02-12, prio:A
-----------------------------
....
...

due:2016-02-10, prio:A
-----------------------------
....
...
```

Just being able to segment by one thing would also be great, but I figure segmenting by multiple things would be a similar amount of effort if taken into account from the start. Simpletask does this, and I find it super helpful.

**Comment by bram85** [comment] 2016-02-10 18:57
This is a duplicate of #22, something on my personal wish list for some time.

**Closed** 2016-02-10 18:58 UTC
